name: juejin_signin

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  juejin-autoSignIn:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Set python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: python -m pip install --upgrade requests
    
    - name: juejin auto sign in
      env:
        JJ_COOKIE: ${{ secrets.JJ_COOKIE }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
      run: python signin.py
